
####
GET http://localhost:3000/
####

####
GET http://localhost:3000/users
####


####
POST http://localhost:3000/users
Content-Type: application/json

{
  "email": "a7@a.com.br",
  "name" : "william2",
  "password" : "123456"
}
####