### subscriber
GET http://localhost:3000/subscribers
###

### subscriber
GET http://localhost:3000/subscribers/1
###

### subscriber
POST http://localhost:3000/subscribers
Content-Type: application/json

{
  "userName":"william",
  "userChannel":"hdodebrasil"
}
###

### subscriber
GET http://localhost:3000/subscribers
###