
####
GET http://localhost:4000/
####

####
GET http://localhost:4000/users
####

####
POST http://localhost:4000/users
Content-Type: application/json

{
  "_name" : "william2",
  "_email": "a7@a.com.br",
  "_password" : "123456"
}
####

####
GET http://localhost:4000/users/Cithx2MN1v4MQjHP
####

####
PUT http://localhost:4000/users/Cithx2MN1v4MQjHP
Content-Type: application/json

{
  "_name" : "william33333",
  "_email": "a3333@a.com.br",
  "_password" : "M123456"
}
####

####
DELETE http://localhost:4000/users/NDtk7pjuZNRQLYfy
####




####
POST http://localhost:4000/users
Content-Type: application/json

{
  "name" : "",
  "email": "dsadsadsa",
  "password" : "123456"
}
####