###
POST http://localhost:3000/game

Content-Type: application/json;
{
  "title":'seila',
  "price":60,
  "year":1980
}
###

###
POST http://localhost:3000/game

body:{
  "title":'seila',
  "price":60,
  "year":1980
}
###