# Generated by Django 2.1.7 on 2020-12-05 02:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='ano_nasc',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1970)]),
        ),
    ]
