# Generated by Django 2.1.7 on 2020-12-05 02:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0002_auto_20201204_2311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='ano_nasc',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1970), django.core.validators.MaxValueValidator(2020)]),
        ),
    ]
