
####
GET http://localhost:8080/
####

####
GET http://localhost:8080/jogadores
####

####
POST http://localhost:8080/jogadores
Content-Type: application/json

{
  "nome" : "william2888",
  "email": "a7@a.com.br",
  "telefoneCelular" : "123456"
}
####

PUT http://localhost:3000/users/Cithx2MN1v4MQjHP
Content-Type: application/json

{
  "_name" : "william3333355",
  "_email": "a3333@a.com.br",
  "_password" : "M123456"
}
####

####
DELETE http://localhost:3000/users/cFvJ9Im8m1oE6SER
####