
#### TESTE API - bem vindo
GET http://localhost:8080/api/v1
####

#### CRUD - CREATE
POST http://localhost:8080/api/v1/jogadores
Content-Type: application/json

{
  "nome" : "william28889",
  "email": "a7@a1.com.br",
  "telefoneCelular" : "123456"
}
####

#### CRUD - READ-all
GET http://localhost:8080/api/v1/jogadores
####

#### CRUD - READ-one
GET http://localhost:8080/api/v1/jogadores/2a57173e-1a54-4fc0-b6ea-57acb5b5acbb
####


#### CRUD - UPDATE
PUT http://localhost:8080/api/v1/jogadores
Content-Type: application/json

{
  "nome" : "william288898",
  "email": "a7@a1.com.br",
  "telefoneCelular" : "123456"
}
####



PUT http://localhost:3000/users/Cithx2MN1v4MQjHP
Content-Type: application/json

{
  "_name" : "william3333355",
  "_email": "a3333@a.com.br",
  "_password" : "M123456"
}
####

####
DELETE http://localhost:3000/users/cFvJ9Im8m1oE6SER
####