####
POST http://localhost:3000/job/add
Content-Type: application/json

{
  "title": "pimba1",
  "salary" : "100",
  "company" : "blau1",
  "email": "a1@a.com.br",
  "new_job" : 1,
  "description": "hdusahdusah1"
}
####


####
POST http://localhost:3000/job/add
Content-Type: application/json

{
  "title": "pimba2",
  "salary" : "200",
  "company" : "blau2",
  "email": "a2@a.com.br",
  "new_job" : 1,
  "description": "hdusahdusah2"
}
####


####
POST http://localhost:3000/job/add
Content-Type: application/json

{
  "title": "pimba3",
  "salary" : "300",
  "company" : "blau3",
  "email": "a3@a.com.br",
  "new_job" : 1,
  "description": "hdusahdusah3"
}
####

####
POST http://localhost:3000/job/add
Content-Type: application/json

{
  "title": "pimba4",
  "salary" : "400",
  "company" : "blau4",
  "email": "a4@a.com.br",
  "new_job" : 0,
  "description": "hdusahdusah4"
}
####