###
### https://marketplace.visualstudio.com/items?itemName=humao.rest-client
### request body rest api
GET http://localhost:3000/games
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiZW1haWwiOiJiQGEuY29tLmJyIiwiaWF0IjoxNjEzMTcwMDI4fQ.hfxdz_gin7CR9aBvFeLO2XvZuBdhbO5-lCEYO7yIvwQ
###

### request body rest api
GET http://localhost:3000/game/5
###

### request body rest api
POST http://localhost:3000/game
Content-Type: application/json

{
  "title" : "seila",
  "price" : 60,
  "year" : 1980
}
###

### request body rest api
DELETE http://localhost:3000/game/5
###


### request body rest api
PUT http://localhost:3000/game/5
Content-Type: application/json

{
  "title" : "Game of Thrones2"
}
###

### request body rest api
POST http://localhost:3000/auth
Content-Type: application/json

{
  "email" : "b@a.com.br",
  "password" : 123456
}
###