# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5a20299064af64769119ac90aa269ae2a311cbd441b29dd83729b68622566847f747c3e73ff63c824dfb693002e89876cb545d8685ebb5652b50e3e5c4cff5bf

test:
  secret_key_base: 4888b6eab72ca6d8d8354309aaf0a858d0961b6e3b0f9a37c95783e48b2c910abaecc31ac85c713d0f76045078e80cf2dd823ef493253992c24322c89cf1418d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
