### get admin
GET http://localhost:3000/admin
### get admin com id
GET http://localhost:3000/admin/35
### acessando via post
POST http://localhost:3000/admin
Content-Type: application/json

{
  "login": "admin",
  "senha": "123456"
}
### acessando via PATCH
PATCH http://localhost:3000/admin
### acessando via PUT
PUT http://localhost:3000/admin/1
### acessando via PUT
DELETE http://localhost:3000/admin/1
###