####
GET http://localhost:3000
####

####
POST http://localhost:3000/user
Content-Type: application/json

{
  "email": "a7@a.com.br",
  "name" : "william2",
  "password" : "123456"
}
####

####
POST http://localhost:3000/user
Content-Type: application/json

{
  "email": "",
  "name" : "william",
  "password" : "123456"
}
####

####
POST http://localhost:3000/user
Content-Type: application/json

{
  "email": "a@a.com.br",
  "name" : "a",
  "password" : "123456"
}
####