#### TESTE API - bem vindo
GET http://localhost:8080/api/v1
####

#### CRUD - CREATE [1/5]
POST http://localhost:8080/api/v1/jogadores
Content-Type: application/json

{
  "nome" : "will3c",
  "email": "a7@a21h.com.br",
  "telefoneCelular" : "123456q"
}
####

#### CRUD - READ-all  [2/5]
GET http://localhost:8080/api/v1/jogadores
####

#### CRUD - READ-one [3/5]
#GET http://localhost:8080/api/v1/jogadores/2a57173e-1a54-4fc0-b6ea-57acb5b5acbb
GET http://localhost:8080/api/v1/jogadores/?email=a7@a21.com.br
####

#### CRUD - UPDATE [4/5]
PUT http://localhost:8080/api/v1/jogadores
Content-Type: application/json

{
  "nome" : "william288898777",
  "email": "a7@a21.com.br",
  "telefoneCelular" : "123456"
}
####

####  CRUD - UPDATE  [4/5]
#DELETE http://localhost:8080/api/v1/jogadores/2a57173e-1a54-4fc0-b6ea-57acb5b5acbb
#DELETE http://localhost:8080/api/v1/jogadores/?email=a7@a1.com.br
DELETE http://localhost:8080/api/v1/jogadores/?email=
####